spring.datasource.url=jdbc:postgresql://dpg-d165ee8gjchc73f48gng-a:5432/jobpulse
spring.datasource.username=pramod
spring.datasource.password=rznlkPNUJz5wQEBqpKMjW4VsGmVMdazb

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port
server.port=8080